import type { ScenarioSpec } from './afterTheEyeOutcomeTypes'

export const AFTER_EYE_SCENARIOS_4: ScenarioSpec[] = [
  {
    id: 'strange_business_breakup_planner',
    category: 'strange_business',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'strange_business',
    badge: 'BIZARRE BUSINESS',
    eligibility: { tagsAny: ['romance'], requiresRelation: 'romantic' },
    headlines: ['{name} Launches a Breakup Planning Agency', 'Flowers In, Shared Passwords Out'],
    beats: [
      '{name} starts a service that organises dignified separations.',
      'Clients receive scripts, key-return envelopes, and optional witnesses trained not to take sides.',
      "The company becomes disturbingly popular before Valentine's Day.",
    ],
    twists: [
      '{romanticName} designs the premium package.',
      'One couple accidentally reconciles during the service.',
    ],
  },
  {
    id: 'strange_business_apology_writer',
    category: 'strange_business',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'strange_business',
    badge: 'SORRY SELLS',
    eligibility: {},
    headlines: [
      '{name} Makes a Fortune Writing Celebrity Apologies',
      'The Notes Sound Human for Once',
    ],
    beats: [
      '{name} quietly writes apology statements for scandal-prone public figures.',
      "Clients praise the service for eliminating phrases such as 'if anyone was offended'.",
      'The business is exposed when three celebrities use the same typo.',
    ],
    twists: [
      'The typo becomes a trademark.',
      '{name} refuses to apologise for the apology business.',
    ],
  },
  {
    id: 'strange_business_rent_a_rival',
    category: 'strange_business',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'strange_business',
    badge: 'ENEMY FOR HIRE',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: [
      '{name} Rents Professional Rivals to Boring Influencers',
      'Every Career Needs a Villain',
    ],
    beats: [
      '{name} builds an agency supplying harmless public feuds to people with no interesting scandals.',
      'Packages include subtweets, award-show side-eye, and one carefully timed unfollow.',
      'The service works until two hired rivals genuinely dislike each other.',
    ],
    twists: ['{rivalName} joins as creative director.', 'The premium feud wins a marketing award.'],
  },
  {
    id: 'strange_business_haunted_airbnb',
    category: 'strange_business',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'strange_business',
    badge: 'GHOST LISTING',
    eligibility: {},
    headlines: [
      '{name} Opens a Haunted Rental With No Ghost',
      'Guests Demand More Paranormal Activity',
    ],
    beats: [
      '{name} markets an old house as a luxury haunted retreat.',
      'Visitors complain that the only frightening feature is the plumbing.',
      'Staff begin manufacturing noises and accidentally convince themselves the place is cursed.',
    ],
    twists: [
      'A real historian makes the property successful.',
      'The fake ghost asks for overtime.',
    ],
  },
  {
    id: 'strange_business_queue_sitter',
    category: 'strange_business',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'strange_business',
    badge: 'TIME TYCOON',
    eligibility: {},
    headlines: [
      '{name} Creates a Professional Queueing Company',
      'Standing Still Becomes Big Business',
    ],
    beats: [
      '{name} hires people to wait in lines for product launches and exclusive restaurants.',
      'Demand explodes when celebrities realise they can arrive precisely when cameras do.',
      'The company develops uniforms, rankings, and an employee of the month.',
    ],
    twists: [
      "The longest queue is for {name}'s own service.",
      'A rival firm starts cutting in line.',
    ],
  },
  {
    id: 'social_media_notes_app',
    category: 'social_media',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'social_media',
    badge: 'APOLOGY LOOP',
    eligibility: {},
    headlines: [
      '{name} Posts Seven Apologies in One Day',
      'Each Statement Corrects the Previous Statement',
    ],
    beats: [
      '{name} tries to resolve a minor misunderstanding with a carefully designed note.',
      'Every edit introduces a new contradiction and a different font.',
      'By evening the original scandal is forgotten and the apology process is the scandal.',
    ],
    twists: [
      'The designer publishes a behind-the-scenes documentary.',
      'The seventh apology is universally praised.',
    ],
  },
  {
    id: 'social_media_live_filter',
    category: 'social_media',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'social_media',
    badge: 'FILTER FAILURE',
    eligibility: {},
    headlines: [
      "{name}'s Beauty Filter Switches Off Mid-Denial",
      'The Face Was Real. The Product Was Not.',
    ],
    beats: [
      '{name} livestreams a forceful defence of a cosmetic sponsorship.',
      'The filter fails while {name} is claiming no digital enhancement is being used.',
      'The brand deletes the campaign and the clip reaches millions.',
    ],
    twists: ['Sales increase anyway.', '{name} later fronts an honesty campaign.'],
  },
  {
    id: 'social_media_private_public',
    category: 'social_media',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'social_media',
    badge: 'CLOSE FRIENDS DISASTER',
    eligibility: { tagsAny: ['betrayal', 'alliance_broken'], requiresRelation: 'ally' },
    headlines: ['{name} Posts the Private Rant Publicly', 'The Green Circle Was Not There'],
    beats: [
      '{name} records a harsh message intended for a tiny private audience.',
      'The clip appears publicly and names {allyName}, two producers, and an innocent hairdresser.',
      'Deletions fail because fans subtitle the rant within minutes.',
    ],
    twists: [
      'The hairdresser gains thousands of followers.',
      '{allyName} replies with a single punctuation mark.',
    ],
  },
  {
    id: 'social_media_account_hacked',
    category: 'social_media',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'social_media',
    badge: 'HACKED — MAYBE',
    eligibility: {},
    headlines: [
      '{name} Blames a Hacker Who Has Excellent Grammar',
      'The Mystery Poster Uses the Same Catchphrase',
    ],
    beats: [
      '{name} claims a controversial series of posts came from an intruder.',
      'Cybersecurity experts note the supposed hacker uses {possessive} favourite emoji and promotes an upcoming appearance.',
      'The explanation remains unproven but strangely effective.',
    ],
    twists: [
      'The hacker books better interviews than {name}.',
      'The account later thanks the hacker.',
    ],
  },
  {
    id: 'social_media_silence_strategy',
    category: 'social_media',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'social_media',
    badge: 'SILENCE WINS',
    eligibility: { tagsAny: ['low_profile', 'early_exit'] },
    headlines: [
      '{name} Refuses to Post and Becomes More Famous',
      'The Blank Feed Everyone Watches',
    ],
    beats: [
      '{name} deletes every social account after the finale.',
      'Fan pages treat each public sighting like a rare astronomical event.',
      'The refusal to perform online creates more mystique than constant content.',
    ],
    twists: ['The first post is a picture of a chair.', 'The chair receives sponsorship offers.'],
  },
  {
    id: 'reality_tv_obsession_six_shows',
    category: 'reality_tv_obsession',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'reality_tv_obsession',
    badge: 'REALITY RELAPSE',
    eligibility: {},
    headlines: ['{name} Joins Six Reality Shows in One Year', 'No Format Is Safe'],
    beats: [
      '{name} accepts every television offer after the finale.',
      'Dating, cooking, survival, dance, and renovation programmes all feature the same dramatic entrance.',
      'Viewers lose track of which show {name} is currently being eliminated from.',
    ],
    twists: [
      'One network accidentally crowns {name} twice.',
      'The cooking show reveals unexpected talent.',
    ],
  },
  {
    id: 'reality_tv_obsession_self_produced_house',
    category: 'reality_tv_obsession',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'reality_tv_obsession',
    badge: 'THE HOUSE AT HOME',
    eligibility: {},
    headlines: ['{name} Installs Cameras in the Apartment', 'Nobody Commissioned Season Two'],
    beats: [
      '{name} recreates the show experience at home and streams daily household routines.',
      'Friends receive microphones at the door and visitors are asked to nominate someone before leaving.',
      'The audience shrinks to twelve loyal viewers and one concerned landlord.',
    ],
    twists: ['The landlord wins the public vote.', 'A small network buys the format as a comedy.'],
  },
  {
    id: 'reality_tv_obsession_reunion_crasher',
    category: 'reality_tv_obsession',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'reality_tv_obsession',
    badge: 'UNINVITED RETURN',
    eligibility: {},
    headlines: ['{name} Appears at Every Reunion — Even Other Shows', 'Security Knows the Outfit'],
    beats: [
      '{name} begins turning up at reunion specials for programmes never joined.',
      'The same confident wave carries {object} past three red carpets before organisers compare guest lists.',
      'A network finally offers a role reviewing reunions from outside the venue.',
    ],
    twists: ['The reviews become popular.', '{name} is accidentally invited to host one.'],
  },
  {
    id: 'reality_tv_obsession_audition_coach',
    category: 'reality_tv_obsession',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'reality_tv_obsession',
    badge: 'CASTING GURU',
    eligibility: {},
    headlines: [
      '{name} Coaches Future Housemates to Cry on Cue',
      'The Workshop Includes a Fake Eviction',
    ],
    beats: [
      '{name} opens an academy for reality-TV applicants.',
      'Students practise entrances, strategic silences, and looking shocked at information they already know.',
      'Casting producers publicly mock the school and privately recruit from it.',
    ],
    twists: [
      'The best student refuses to credit {name}.',
      'The fake eviction becomes too emotional.',
    ],
  },
  {
    id: 'reality_tv_obsession_producer_turn',
    category: 'reality_tv_obsession',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'reality_tv_obsession',
    badge: 'BEHIND THE CAMERA',
    eligibility: { tagsAny: ['strategic', 'winner', 'late_game'], requiresRelation: 'rival' },
    headlines: [
      '{name} Becomes the Producer Everyone Fears',
      'The Housemate Learns Where the Buttons Are',
    ],
    beats: [
      '{name} moves behind the scenes and develops a reputation for spotting manufactured drama instantly.',
      'Contestants complain that every planned trick is anticipated before filming.',
      'The former housemate creates a hit format with fewer speeches and better snacks.',
    ],
    twists: ['The first contestant is {rivalName}.', 'The snack budget wins industry praise.'],
  },
  {
    id: 'conspiracy_red_string_room',
    category: 'conspiracy',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'conspiracy',
    badge: 'CONSPIRACY HQ',
    eligibility: {},
    headlines: [
      '{name} Covers an Entire Room in Red String',
      'Every Eviction Leads to the Same Producer',
    ],
    beats: [
      '{name} dedicates years to proving the season was manipulated.',
      'Maps connect challenge results, breakfast choices, moon phases, and one suspiciously repeated cushion.',
      'A livestream tour of the evidence room attracts both fans and fire inspectors.',
    ],
    twists: [
      'One tiny scheduling claim is actually correct.',
      'The cushion is later sold at auction.',
    ],
  },
  {
    id: 'conspiracy_missing_day',
    category: 'conspiracy',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'conspiracy',
    badge: 'THE LOST DAY',
    eligibility: { tagsAny: ['alliance_broken', 'low_profile'], requiresRelation: 'ally' },
    headlines: ['{name} Insists the Season Had a Secret Extra Day', 'Nobody Remembers Tuesday'],
    beats: [
      '{name} becomes convinced that one day of filming was erased.',
      "The theory rests on mismatched outfits, a missing carton of milk, and {allyName}'s vague diary entry.",
      'Former housemates disagree about the date but admit the milk is difficult to explain.',
    ],
    twists: [
      'The carton appears in unused footage.',
      '{allyName} reveals the diary entry was about laundry.',
    ],
  },
  {
    id: 'conspiracy_clone_theory',
    category: 'conspiracy',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'conspiracy',
    badge: 'DOUBLE TROUBLE',
    eligibility: { tagsAny: ['twin_shock'] },
    headlines: [
      '{name} Claims a Housemate Was Replaced by a Double',
      'The Ears Do Not Match, Says {name}',
    ],
    beats: [
      '{name} publishes side-by-side images alleging a contestant was secretly substituted.',
      'The theory gains traction because the photographs use different lighting and opposite camera angles.',
      "Experts dismiss it while fans begin measuring everybody's ears.",
    ],
    twists: [
      'Twin Shock makes the theory look less ridiculous.',
      '{name} accidentally compares two photos of the same day.',
    ],
  },
  {
    id: 'conspiracy_jury_math',
    category: 'conspiracy',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'conspiracy',
    badge: 'VOTE MATHEMATICS',
    eligibility: {},
    headlines: ['{name} Recounts the Tribunal Votes Every Night', 'The Numbers Still Add Up'],
    beats: [
      '{name} refuses to accept the finale result and develops increasingly elaborate vote models.',
      'Spreadsheets account for seating order, envelope weight, and how long each juror blinked.',
      'The calculations prove the official result repeatedly, which only deepens the suspicion.',
    ],
    twists: [
      'A maths channel reviews the model respectfully.',
      '{name} later sells the spreadsheet as a game.',
    ],
  },
  {
    id: 'conspiracy_theory_podcast',
    category: 'conspiracy',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'conspiracy',
    badge: 'PARANOIA PAYS',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: [
      "{name}'s Conspiracy Podcast Becomes a Hit",
      'Wrong About Everything, Excellent Production',
    ],
    beats: [
      '{name} launches a weekly investigation into supposed hidden messages from the season.',
      'The theories are absurd but the sound design, research notes, and cliffhangers are exceptional.',
      'Listeners tune in as entertainment and advertisers follow.',
    ],
    twists: [
      'The final episode debunks the entire series.',
      '{rivalName} becomes a recurring sceptic.',
    ],
  },
]
