import type { ScenarioSpec } from './afterTheEyeOutcomeTypes'

export const AFTER_EYE_SCENARIOS_2: ScenarioSpec[] = [
  {
    id: 'cheating_scandal_hotel_lobby',
    category: 'cheating_scandal',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'cheating_scandal',
    badge: 'CAUGHT',
    eligibility: { tagsAny: ['romance', 'controversial'], requiresRelation: 'romantic' },
    headlines: [
      '{name} Is Caught in the Wrong Hotel Lobby',
      'One Lift, Two Relationships, No Explanation',
    ],
    beats: [
      '{name} is photographed entering a hotel with {romanticName} while publicly dating someone else.',
      'The pair claims they were discussing charity work at 2:14 a.m. beside a room-service trolley.',
      'Three contradictory statements appear before breakfast.',
    ],
    twists: [
      'The charity is registered the next day.',
      'The trolley attendant becomes a key witness.',
    ],
  },
  {
    id: 'cheating_scandal_reunion_triangle',
    category: 'cheating_scandal',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'cheating_scandal',
    badge: 'TRIANGLE EXPLODES',
    eligibility: { tagsAny: ['romance'], requiresRelation: 'romantic' },
    headlines: [
      "{name}'s Reunion Flirtation Becomes a Three-Person Crisis",
      'Old Sparks, New Partners, Live Cameras',
    ],
    beats: [
      '{name} reconnects with {romanticName} during a reunion special.',
      'Their current partners discover the private messages while the aftershow is still broadcasting.',
      'The reunion receives record ratings and four separate apology videos.',
    ],
    twists: ['Both original couples swap partners.', 'The network orders a follow-up special.'],
  },
  {
    id: 'cheating_scandal_wrong_caption',
    category: 'cheating_scandal',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'cheating_scandal',
    badge: 'POSTED BY MISTAKE',
    eligibility: {},
    headlines: [
      '{name} Uploads the Wrong Anniversary Photo',
      'The Caption Was Sweet. The Person Was Not the Partner.',
    ],
    beats: [
      '{name} posts a romantic anniversary tribute using a photo taken with somebody else.',
      'The image stays online for nine minutes, long enough for fans to identify the restaurant, date, and dessert.',
      '{name} blames an assistant who publicly denies having access to the account.',
    ],
    twists: ['The dessert becomes a trending search.', 'The assistant gets a better job.'],
  },
  {
    id: 'cheating_scandal_double_booking',
    category: 'cheating_scandal',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'cheating_scandal',
    badge: 'DOUBLE-BOOKED LOVE',
    eligibility: {},
    headlines: [
      '{name} Schedules Two Dates at the Same Restaurant',
      'Table Seven Meets Table Nine',
    ],
    beats: [
      '{name} accidentally books overlapping dinners with two romantic interests.',
      'A waiter notices identical flowers and seats the parties within direct view of each other.',
      'The restaurant livestreams nothing, but every customer somehow has footage.',
    ],
    twists: ['The two dates become friends.', '{name} is banned from making online reservations.'],
  },
  {
    id: 'cheating_scandal_fake_cheating',
    category: 'cheating_scandal',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'cheating_scandal',
    badge: "SCANDAL THAT WASN'T",
    eligibility: {},
    headlines: [
      '{name} Is Accused of Cheating on a Relationship That Never Existed',
      'The Couple Denies Being a Couple',
    ],
    beats: [
      '{name} is linked to two people after months of deliberately vague publicity.',
      'Both supposed partners deny any romance, then become offended that the public believed the other one.',
      'The scandal collapses into a debate about whether staged dating counts as dating.',
    ],
    twists: [
      'All three sign the same management agency.',
      'A documentary buys the rights to the confusion.',
    ],
  },
  {
    id: 'public_feud_podcast_feud',
    category: 'public_feud',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'public_feud',
    badge: 'MIC WAR',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: [
      '{name} and {rivalName} Destroy a Podcast in Episode One',
      'Former Rivals Last Twenty-Three Minutes',
    ],
    beats: [
      '{name} launches a reconciliation podcast with {rivalName}.',
      'The opening pleasantries collapse when both bring different lists of topics the other promised not to mention.',
      'The microphones stay on through a commercial break and the partnership ends live.',
    ],
    twists: [
      'The unaired break becomes the most downloaded clip.',
      'They return for episode two to argue about episode one.',
    ],
  },
  {
    id: 'public_feud_lawsuit_song',
    category: 'public_feud',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'public_feud',
    badge: 'FEUD GOES MUSICAL',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: ['{name} Answers a Lawsuit With a Diss Track', 'Legal Team Begs for Silence'],
    beats: [
      '{name} receives a formal complaint from {rivalName} and responds by recording a song.',
      'The lyrics reveal more evidence than the opposing lawyers had requested.',
      'The track charts briefly while the case becomes much harder to defend.',
    ],
    twists: ['The judge quotes the chorus.', '{rivalName} releases an acoustic reply.'],
  },
  {
    id: 'public_feud_petty_products',
    category: 'public_feud',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'public_feud',
    badge: 'PETTY BUSINESS',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: [
      "{name} Launches a Product Named After {rivalName}'s Worst Moment",
      'The Feud Reaches the Gift Shop',
    ],
    beats: [
      '{name} turns an old argument with {rivalName} into a novelty product.',
      'Fans buy it as a joke until the rival launches a competing version with better packaging.',
      'Both sides claim victory while accountants quietly celebrate.',
    ],
    twists: [
      'The products are manufactured in the same factory.',
      'The rivals eventually merge the brands.',
    ],
  },
  {
    id: 'public_feud_award_seating',
    category: 'public_feud',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'public_feud',
    badge: 'RED CARPET WAR',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: [
      '{name} Refuses a Seat Near {rivalName}',
      'One Awards Show, Seventeen Seating Charts',
    ],
    beats: [
      '{name} demands to be placed far from {rivalName} at a television awards ceremony.',
      'Organisers redraw the room repeatedly until the two are accidentally placed back-to-back.',
      "A chair movement becomes the night's most analysed footage.",
    ],
    twists: ['Neither wins an award.', 'The chairs are auctioned as a pair.'],
  },
  {
    id: 'public_feud_feud_business',
    category: 'public_feud',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'public_feud',
    badge: 'ENEMIES CASH IN',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: ['{name} Turns the Feud Into a Business', 'Hate, But Make It Profitable'],
    beats: [
      '{name} and {rivalName} agree to sell tickets to a public debate.',
      'The event expands into a tour after audiences discover the insults are weirdly well rehearsed.',
      'The rivals earn enough money to postpone reconciliation indefinitely.',
    ],
    twists: ['They share an accountant.', 'The final show ends with a suspiciously friendly hug.'],
  },
  {
    id: 'betrayal_memoir_exposes_ally',
    category: 'betrayal',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'betrayal',
    badge: 'BETRAYAL IN PRINT',
    eligibility: { tagsAny: ['betrayal', 'alliance_broken'], requiresRelation: 'ally' },
    headlines: ['{name} Exposes {allyName} in a Tell-All', 'The Alliance Ends on Page Forty-Seven'],
    beats: [
      '{name} publishes private messages from {allyName} while promoting a book about loyalty.',
      'The leaked conversation reveals both had planned to blame the other if the season went badly.',
      'The friendship collapses through footnotes and competing audiobook versions.',
    ],
    twists: [
      'The messages were already public in a forgotten livestream.',
      'The book dedication still thanks {allyName}.',
    ],
  },
  {
    id: 'betrayal_business_backstab',
    category: 'betrayal',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'betrayal',
    badge: 'PARTNERSHIP AMBUSH',
    eligibility: { tagsAny: ['betrayal', 'alliance_broken'], requiresRelation: 'ally' },
    headlines: ['{name} Locks {allyName} Out of Their Own Launch', 'Best Friends, One Password'],
    beats: [
      '{name} starts a business with {allyName} and changes every account password hours before launch.',
      "Customers watch the former allies fight through the brand's official support chat.",
      'The website sells out only because people think the chaos is performance art.',
    ],
    twists: [
      'The passwords were written on the launch cake.',
      'The pair reunites solely to divide the profits.',
    ],
  },
  {
    id: 'betrayal_wedding_secret',
    category: 'betrayal',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'betrayal',
    badge: 'RECEPTION REVEAL',
    eligibility: { tagsAny: ['betrayal', 'alliance_broken'], requiresRelation: 'ally' },
    headlines: [
      "{name} Reveals {allyName}'s Secret at the Wedding",
      'The Toast That Ended a Friendship',
    ],
    beats: [
      '{name} is invited to give a warm wedding speech for {allyName}.',
      'The toast drifts into an old house secret that nobody outside the cast was meant to know.',
      'Music starts early in an unsuccessful attempt to drown out the final sentence.',
    ],
    twists: ['Half the guests already knew.', "The videographer labels the clip 'best speech'."],
  },
  {
    id: 'betrayal_secret_groupchat',
    category: 'betrayal',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'betrayal',
    badge: 'GROUP CHAT LEAK',
    eligibility: { tagsAny: ['alliance_broken', 'betrayal'], requiresRelation: 'ally' },
    headlines: ['{name} Leaks the Alliance Group Chat', 'Every Screenshot Has a Different Crop'],
    beats: [
      '{name} accidentally uploads a screen recording containing months of messages with {allyName}.',
      'Fans analyse typing indicators, deleted messages, and a suspicious contact nickname.',
      'The leak proves the alliance was both more loyal and more petty than anyone expected.',
    ],
    twists: [
      'The most damaging message is about takeaway food.',
      '{allyName} responds with the missing screenshots.',
    ],
  },
  {
    id: 'betrayal_betrayal_redemption',
    category: 'betrayal',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'betrayal',
    badge: 'FORGIVEN — AT A PRICE',
    eligibility: { tagsAny: ['betrayal', 'alliance_broken'], requiresRelation: 'ally' },
    headlines: ["{name} Buys Back {allyName}'s Trust", 'The Most Expensive Apology of the Year'],
    beats: [
      '{name} publicly admits betraying {allyName} and stages an apology with no sponsorships.',
      'The sincerity shocks viewers until a giant wrapped gift is wheeled onto the set.',
      'The friendship resumes under a written agreement banning surprise interviews.',
    ],
    twists: [
      'The gift is a framed screenshot of the betrayal.',
      'Their reunion special becomes a hit.',
    ],
  },
  {
    id: 'financial_success_boring_investment',
    category: 'financial_success',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'financial_success',
    badge: 'SECRET MILLIONAIRE',
    eligibility: { tagsAny: ['low_profile', 'early_exit'] },
    headlines: ['{name} Quietly Makes a Fortune', 'No Yacht, No Speech, Just Compound Interest'],
    beats: [
      '{name} ignores the influencer circuit and invests the appearance money in an unglamorous logistics company.',
      'The company expands while other cast members post sponsored candles.',
      '{name} becomes the richest housemate and continues wearing the same finale jacket.',
    ],
    twists: [
      "The company delivers half the cast's merchandise.",
      'Nobody believes the fortune until tax records leak.',
    ],
  },
  {
    id: 'financial_success_snack_empire',
    category: 'financial_success',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'financial_success',
    badge: 'SNACK TYCOON',
    eligibility: { requiresRelation: 'rival' },
    headlines: ["{name}'s Late-Night Snack Becomes an Empire", 'The Recipe Was Almost an Accident'],
    beats: [
      '{name} recreates a strange snack eaten repeatedly in the house.',
      'A supermarket order turns the joke into a national product with five unnecessary flavours.',
      'The packaging uses a dramatic screenshot of {name} staring into the fridge.',
    ],
    twists: [
      'The least appealing flavour becomes the bestseller.',
      '{rivalName} requests a royalty for suggesting the original snack.',
    ],
  },
  {
    id: 'financial_success_appearance_fees',
    category: 'financial_success',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'financial_success',
    badge: 'BOOKED SOLID',
    eligibility: {},
    headlines: [
      '{name} Perfects the Paid Appearance',
      'Forty Minutes, One Selfie Wall, Excellent Invoice',
    ],
    beats: [
      '{name} discovers that nightclub openings and shopping-centre appearances pay better than long interviews.',
      'A strict seven-minute speech and twelve-minute photo schedule becomes famous among event planners.',
      '{name} works less than everyone else and earns more than most.',
    ],
    twists: [
      'One venue hires a lookalike by mistake.',
      'The schedule is later taught in a business seminar.',
    ],
  },
  {
    id: 'financial_success_auction_props',
    category: 'financial_success',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'financial_success',
    badge: 'HOUSE RELIC BONANZA',
    eligibility: {},
    headlines: [
      '{name} Auctions Every Meaningless Souvenir',
      'Fans Pay Thousands for a Bent Spoon',
    ],
    beats: [
      '{name} saves ordinary objects associated with the season and sells them as authenticated memorabilia.',
      'Bidding escalates over a robe belt, a cracked mug, and a note nobody can read.',
      'The collection funds a comfortable new home.',
    ],
    twists: ['The most expensive item is not from the house.', 'A museum requests the bent spoon.'],
  },
  {
    id: 'financial_success_app_success',
    category: 'financial_success',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'financial_success',
    badge: 'TECH SURPRISE',
    eligibility: {},
    headlines: [
      '{name} Launches an App That Actually Works',
      'The Rare Celebrity Product With Customer Support',
    ],
    beats: [
      '{name} funds a simple app based on organising group decisions.',
      'Users praise it for solving arguments without requiring anyone to watch a motivational video.',
      'The app grows internationally while {name} refuses to explain the code.',
    ],
    twists: [
      'The developer is a former fan account administrator.',
      "The app is used to plan a rival's wedding.",
    ],
  },
]
