import type { ScenarioSpec } from './afterTheEyeOutcomeTypes'

export const AFTER_EYE_SCENARIOS_1: ScenarioSpec[] = [
  {
    id: 'sudden_fame_airport_icon',
    category: 'sudden_fame',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'sudden_fame',
    badge: 'OVERNIGHT ICON',
    eligibility: { tagsAny: ['fan_favorite', 'public_favorite'], requiresRelation: 'rival' },
    headlines: ['{name} Causes Airport Chaos', 'Fans Mistake {name} for Global Royalty'],
    beats: [
      '{name} leaves the finale with one viral reaction clip and wakes up to a crowd at the airport.',
      'Security closes two entrances after fans begin chanting a quote {name} does not remember saying.',
      'A luggage brand signs {object} before the suitcase even reaches baggage claim.',
    ],
    twists: [
      'The famous quote was actually said by {rivalName}.',
      'The airport later sells a commemorative snack named after {name}.',
    ],
  },
  {
    id: 'sudden_fame_breakfast_face',
    category: 'sudden_fame',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'sudden_fame',
    badge: 'FRONT-PAGE FACE',
    eligibility: { tagsAny: ['fan_favorite', 'winner', 'runner_up'] },
    headlines: ['{name} Wins Breakfast Television', 'One Interview, Seven Contracts'],
    beats: [
      "{name} appears on a morning show for six minutes and becomes the season's most copied expression.",
      'Brands compete to sponsor the mug, robe, and spoon visible during the interview.',
      'The host quietly admits the segment was supposed to be about someone else.',
    ],
    twists: [
      'The robe becomes more famous than the winner.',
      '{name} later buys the studio chair at auction.',
    ],
  },
  {
    id: 'sudden_fame_meme_empire',
    category: 'sudden_fame',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'sudden_fame',
    badge: 'MEME EMPIRE',
    eligibility: {},
    headlines: ["{name}'s Face Takes Over the Internet", 'The Screenshot That Paid the Rent'],
    beats: [
      'A freeze-frame of {name} reacting to the finale becomes the universal answer to bad news.',
      'The image appears on billboards, birthday cakes, and one municipal warning sign.',
      '{name} licenses the meme and turns embarrassment into a very respectable income.',
    ],
    twists: [
      'The original photographer asks for royalties.',
      'The meme is later displayed in a small modern-art exhibition.',
    ],
  },
  {
    id: 'sudden_fame_fake_entourage',
    category: 'sudden_fame',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'sudden_fame',
    badge: 'FAME FEVER',
    eligibility: {},
    headlines: ['{name} Hires an Entourage of Twelve', 'Too Famous to Carry a Phone'],
    beats: [
      '{name} decides ordinary life is no longer compatible with the new level of fame.',
      "A stylist, a spiritual adviser, two assistants, and a person described only as 'vibe control' begin following {object}.",
      'The entourage costs more per week than {name} actually earns.',
    ],
    twists: [
      'The vibe controller becomes the real celebrity.',
      '{name} fires everyone through a group poll.',
    ],
  },
  {
    id: 'sudden_fame_fan_stampede',
    category: 'sudden_fame',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'sudden_fame',
    badge: 'FAME NIGHTMARE',
    eligibility: {},
    headlines: ["{name}'s Meet-and-Greet Goes Off the Rails", 'The Selfie Queue Nobody Could Stop'],
    beats: [
      '{name} announces a tiny café appearance and accidentally attracts a crowd the venue cannot hold.',
      'The coffee machine breaks, three fake managers appear, and a rival fan club claims the event was sabotaged.',
      '{name} escapes through the kitchen wearing an apron and refuses public brunches for months.',
    ],
    twists: [
      'The apron sells online for an absurd price.',
      'The café rebrands the disaster as an annual festival.',
    ],
  },
  {
    id: 'career_triumph_prime_time_host',
    category: 'career_triumph',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'career_triumph',
    badge: 'NEW PRIME-TIME STAR',
    eligibility: { tagsAny: ['winner', 'runner_up', 'fan_favorite'], requiresRelation: 'ally' },
    headlines: ['{name} Steals the Show', 'From Housemate to Host'],
    beats: [
      '{name} is hired to present a late-night reality recap and immediately outshines the planned celebrity guest.',
      'Producers expand the segment into a weekly show built around {possessive} dry reactions.',
      'Ratings climb whenever {name} ignores the teleprompter.',
    ],
    twists: [
      '{allyName} becomes the first recurring guest.',
      'The original host asks to join as a correspondent.',
    ],
  },
  {
    id: 'career_triumph_luxury_designer',
    category: 'career_triumph',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'career_triumph',
    badge: 'LUXURY LAUNCH',
    eligibility: { tagsAny: ['fan_favorite', 'public_favorite'], requiresRelation: 'rival' },
    headlines: ['{name} Turns House Style Into High Fashion', 'The Robe That Became a Runway'],
    beats: [
      '{name} launches a clothing line inspired by the most dramatic outfits from the season.',
      'The first collection sells out despite including a coat with four decorative microphones.',
      'Fashion critics call it ridiculous, then quietly request samples.',
    ],
    twists: ['The microphone coat wins a design prize.', '{rivalName} is photographed wearing it.'],
  },
  {
    id: 'career_triumph_documentary_voice',
    category: 'career_triumph',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'career_triumph',
    badge: 'SERIOUS CAREER',
    eligibility: {},
    headlines: ['{name} Finds an Unexpected Calling', 'The Voice Nobody Knew They Needed'],
    beats: [
      '{name} records narration for a documentary as a favour and becomes known for a strangely calming voice.',
      'Nature films, crime reconstructions, and sleep apps all begin requesting the same dramatic whisper.',
      "{name} earns more by saying 'meanwhile' than during the entire season.",
    ],
    twists: [
      'A sleep app causes listeners to quote the finale in their dreams.',
      'The documentary wins an award for sound.',
    ],
  },
  {
    id: 'career_triumph_restaurant_rescue',
    category: 'career_triumph',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'career_triumph',
    badge: 'SECOND ACT',
    eligibility: {},
    headlines: ['{name} Saves a Failing Restaurant', 'Dinner, Drama, and a Full Booking List'],
    beats: [
      '{name} invests in a nearly empty neighbourhood restaurant after becoming obsessed with its soup.',
      "A blunt social-media review brings queues around the block and forces the chef to add a 'no filming' rule.",
      'The restaurant survives and names the corner table after {name}.',
    ],
    twists: ['The famous soup came from a packet.', '{name} never learns the recipe.'],
  },
  {
    id: 'career_triumph_weather_presenter',
    category: 'career_triumph',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'career_triumph',
    badge: 'UNLIKELY EXPERT',
    eligibility: {},
    headlines: [
      "{name} Becomes the Nation's Favourite Weather Presenter",
      'Forecast: Ninety Percent Drama',
    ],
    beats: [
      '{name} fills in for a local weather presenter and delivers the forecast like an eviction ceremony.',
      "Viewers begin tuning in just to hear whether the rain has 'the votes to stay'.",
      'The station keeps {name}, although meteorologists remain visibly tired.',
    ],
    twists: [
      'A storm is named unofficially after {name}.',
      'The forecast catchphrase becomes a ringtone.',
    ],
  },
  {
    id: 'career_disaster_memoir_fiction',
    category: 'career_disaster',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'career_disaster',
    badge: 'BOOK BOMBSHELL',
    eligibility: { tagsAny: ['controversial', 'betrayal'], requiresRelation: 'ally' },
    headlines: [
      "{name}'s Memoir Contains Almost No Truth",
      'The Tell-All That Told Too Much — Incorrectly',
    ],
    beats: [
      '{name} publishes a memoir promising every secret from the house.',
      'Former housemates identify invented conversations, impossible dates, and an entire week that never happened.',
      'The publisher moves the book from biography to fiction without changing the cover.',
    ],
    twists: [
      '{name} wins an award for imaginative writing.',
      '{allyName} admits one chapter is accidentally accurate.',
    ],
  },
  {
    id: 'career_disaster_perfume_disaster',
    category: 'career_disaster',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'career_disaster',
    badge: 'SCENT SCANDAL',
    eligibility: {},
    headlines: [
      "{name}'s Luxury Perfume Clears a Shopping Centre",
      'Aroma of Ambition, Notes of Panic',
    ],
    beats: [
      "{name} launches a fragrance described as 'the smell of winning'.",
      'The first public spray triggers alarms, evacuates a boutique, and stains a marble display purple.',
      'The product is recalled before the launch speech ends.',
    ],
    twists: [
      'Collectors drive the recalled bottles to ridiculous prices.',
      'The formula becomes an industrial cleaner.',
    ],
  },
  {
    id: 'career_disaster_podcast_zero',
    category: 'career_disaster',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'career_disaster',
    badge: 'MICROPHONE MELTDOWN',
    eligibility: { tagsAny: ['rivalry', 'controversial'], requiresRelation: 'rival' },
    headlines: [
      "{name}'s Podcast Loses Its Guest Before Episode One",
      'The Show That Ended During the Intro',
    ],
    beats: [
      '{name} announces a major interview podcast with dramatic lighting and no confirmed guests.',
      'The first guest leaves after being introduced by the wrong name three times.',
      'Episode one is replaced by a forty-minute explanation of why episode one failed.',
    ],
    twists: [
      "The explanation becomes the show's only hit.",
      '{rivalName} launches a parody podcast the same afternoon.',
    ],
  },
  {
    id: 'career_disaster_acting_cut',
    category: 'career_disaster',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'career_disaster',
    badge: 'CUT FROM EVERYTHING',
    eligibility: {},
    headlines: ["{name}'s Acting Debut Lasts Eleven Seconds", 'Hollywood Said Maybe — Then Edited'],
    beats: [
      '{name} lands a small role in a glossy drama and tells every interviewer it is a career-defining performance.',
      'The final cut keeps only the back of {possessive} head and half a cough.',
      '{name} hosts a premiere party anyway and pauses the scene to point at the screen.',
    ],
    twists: [
      'The cough becomes a fan favourite.',
      'The deleted scenes leak and are somehow worse.',
    ],
  },
  {
    id: 'career_disaster_motivational_tour',
    category: 'career_disaster',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'career_disaster',
    badge: 'INSPIRATION CRISIS',
    eligibility: {},
    headlines: [
      "{name}'s Motivational Tour Needs Motivation",
      'Believe in Yourself — Refunds Pending',
    ],
    beats: [
      "{name} launches a seminar series about discipline, loyalty, and 'owning the room'.",
      'The opening date starts late because {name} forgets the venue and the audience writes the speech themselves.',
      'Three dates are cancelled and the remaining one is converted into a public apology.',
    ],
    twists: [
      "The audience's improvised speech goes viral.",
      '{name} later sells a course on recovering from failed courses.',
    ],
  },
  {
    id: 'romance_fake_romance_real',
    category: 'romance',
    tone: 'good',
    weight: 1.0,
    cooldownGroup: 'romance',
    badge: 'SECRET LOVE',
    eligibility: { tagsAny: ['romance'], requiresRelation: 'romantic' },
    headlines: [
      "{name}'s Fake Romance Becomes Alarmingly Real",
      'Publicity Stunt Ends in Matching Keys',
    ],
    beats: [
      '{name} agrees to stage a romance with {romanticName} for magazine attention.',
      'The pair begins arguing over whose turn it is to pretend, then quietly moves in together.',
      'Their management teams discover the relationship is genuine from a shared grocery receipt.',
    ],
    twists: [
      'The breakup announcement is cancelled.',
      "They later insist the entire thing was 'always private'.",
    ],
  },
  {
    id: 'romance_rival_wedding',
    category: 'romance',
    tone: 'excellent',
    weight: 1.0,
    cooldownGroup: 'romance',
    badge: 'WEDDING SHOCK',
    eligibility: { tagsAny: ['rivalry'], requiresRelation: 'rival' },
    headlines: ['{name} Marries Into the Rival Camp', 'The Ceremony Nobody Saw Coming'],
    beats: [
      '{name} begins dating a close relative of {rivalName} after an awkward reunion dinner.',
      'The relationship advances so quickly that former enemies are seated at the same wedding table.',
      '{rivalName} gives a speech that starts hostile and ends in tears.',
    ],
    twists: [
      'The cake contains a tiny replica of the house.',
      'The marriage lasts longer than the rivalry.',
    ],
  },
  {
    id: 'romance_engagement_sponsor',
    category: 'romance',
    tone: 'bad',
    weight: 1.0,
    cooldownGroup: 'romance',
    badge: 'LOVE FOR SALE',
    eligibility: {},
    headlines: [
      "{name}'s Engagement Is Sponsored by Six Brands",
      'The Ring Came With a Discount Code',
    ],
    beats: [
      '{name} announces an engagement through a twelve-slide advertisement.',
      'Fans spot three different ring boxes and a contract reflected in the champagne bucket.',
      'The couple spends the honeymoon filming product tutorials in separate rooms.',
    ],
    twists: [
      'The sponsor extends the engagement for another month.',
      'The wedding is cancelled but the content performs well.',
    ],
  },
  {
    id: 'romance_mystery_date',
    category: 'romance',
    tone: 'neutral',
    weight: 1.0,
    cooldownGroup: 'romance',
    badge: 'MYSTERY COMPANION',
    eligibility: {},
    headlines: [
      '{name} Is Seen With the Same Mystery Date Everywhere',
      'Seven Sightings, Zero Confirmation',
    ],
    beats: [
      '{name} is photographed leaving restaurants, cinemas, and a pet shop with an unidentified companion.',
      'Every former housemate denies knowing the person while clearly knowing the person.',
      '{name} refuses to comment and posts a picture of two toothbrushes instead.',
    ],
    twists: [
      'The mystery date is a cousin helping with a move.',
      'The toothbrush post was an advertisement.',
    ],
  },
  {
    id: 'romance_wedding_reveal',
    category: 'romance',
    tone: 'tragic',
    weight: 1.0,
    cooldownGroup: 'romance',
    badge: 'ALTAR BOMBSHELL',
    eligibility: { tagsAny: ['rivalry', 'controversial'], requiresRelation: 'rival' },
    headlines: ["{name}'s Wedding Stops at the Objection", 'A Former Housemate Brings Receipts'],
    beats: [
      '{name} reaches the altar after a whirlwind public romance.',
      '{rivalName} appears during the ceremony with screenshots suggesting the relationship began before another one ended.',
      'The guests remain seated because nobody is certain whether the confrontation is part of the entertainment.',
    ],
    twists: [
      'The screenshots belong to a different couple.',
      'The reception continues without the wedding.',
    ],
  },
]
