import type { CastleRescueLevelDefinition } from './castleRescuePuzzleTypes';

export const CASTLE_RESCUE_LEVELS: CastleRescueLevelDefinition[] = [
  {
    id: 'floodgate-foyer',
    name: 'Floodgate Foyer',
    width: 5,
    height: 6,
    blockerDensity: 'none',
    summary: 'A pure rescue drill: clear the foyer before the water reaches the throne.',
    rows: [
      'GGSRG',
      'SGGRG',
      'GSSGS',
      'GSRSG',
      'SGSGS',
      'SGSGG',
    ],
  },
  {
    id: 'ring-ramparts',
    name: 'Ring Ramparts',
    width: 5,
    height: 6,
    blockerDensity: 'none',
    summary: 'A narrow battlement with gaps that funnel the falling gems into risky lanes.',
    rows: [
      '.SRG.',
      'SRSSR',
      'RG.RG',
      'GS.RS',
      'SRSSG',
      '.GRR.',
    ],
  },
  {
    id: 'pillar-cellar',
    name: 'Pillar Cellar',
    width: 5,
    height: 6,
    blockerDensity: 'light',
    summary: 'Crates snag both flanks, so you must peel the sides open before the king can breathe.',
    rows: [
      '.RRS.',
      'S1SRS',
      'SRSSR',
      'GSR1R',
      'GRGSS',
      '.SRS.',
    ],
  },
  {
    id: 'drowned-archives',
    name: 'Drowned Archives',
    width: 5,
    height: 6,
    blockerDensity: 'medium',
    summary: 'Heavy stone slabs need two hits, forcing careful setups while the archives flood.',
    rows: [
      '.SRS.',
      'SR2GR',
      'RSRRS',
      'SG2SG',
      'SRSGR',
      '.RGG.',
    ],
  },
  {
    id: 'cross-current-prison',
    name: 'Crosscurrent Prison',
    width: 5,
    height: 6,
    blockerDensity: 'none',
    summary: 'Split channels funnel the falling crests into a narrow prison shaft that still needs a full clear.',
    rows: [
      '.RGR.',
      'RGSGR',
      'GRSRR',
      'SGGSG',
      '.GSS.',
      '.RRG.',
    ],
  },
];
