export interface NumberTriviaQuestion {
  prompt: string;
  answer: number;
}

export const NUMBER_TRIVIA_QUESTIONS: NumberTriviaQuestion[] = [
  { prompt: 'How many housemates typically compete in a season of The Big Eye?', answer: 16 },
  { prompt: 'In what year did The Big Eye first premiere?', answer: 2000 },
  { prompt: 'How many days does a typical season of The Big Eye last?', answer: 99 },
  { prompt: 'How many votes does it take to eliminate with a house of 10 remaining?', answer: 5 },
  { prompt: 'What is the maximum number of housemates who can be nominated at once?', answer: 2 },
  { prompt: 'How many weeks typically occur in a full season of The Big Eye?', answer: 13 },
  { prompt: 'How many people vote in the finale to crown the winner?', answer: 9 },
  { prompt: 'What is the typical prize amount for winning The Big Eye (in thousands)?', answer: 500 },
  { prompt: 'How many housemates make it to the final two?', answer: 2 },
  { prompt: 'How many LOH competitions occur in a 13-week season?', answer: 13 },
  { prompt: 'In what season did the Power of Safety first appear?', answer: 3 },
  { prompt: 'How many seasons has The Big Eye aired (as of 2024)?', answer: 26 },
  { prompt: 'How many cameras are typically in The Big Eye house?', answer: 94 },
  { prompt: 'What is the age requirement to apply for The Big Eye?', answer: 21 },
  { prompt: 'How many Tribunal members typically vote in the finale?', answer: 9 },
  { prompt: 'How many parts does the Final LOH competition have?', answer: 3 },
  { prompt: 'How many POS competitions occur in a standard week?', answer: 1 },
  { prompt: 'What week does the Tribunal phase typically start?', answer: 5 },
  { prompt: 'How many housemates were in the first season of The Big Eye?', answer: 10 },
  { prompt: 'How many Battle Back Shocks have occurred in The Big Eye history?', answer: 4 },
  { prompt: 'What is 7 x 8?', answer: 56 },
  { prompt: 'What is 12 x 12?', answer: 144 },
  { prompt: 'What is 15 x 4?', answer: 60 },
  { prompt: 'What is 9 x 9?', answer: 81 },
  { prompt: 'How many minutes are in 3 hours?', answer: 180 },
  { prompt: 'What is 20% of 500?', answer: 100 },
  { prompt: 'How many days are in a leap year?', answer: 366 },
  { prompt: 'What is the square root of 64?', answer: 8 },
  { prompt: 'How many sides does a hexagon have?', answer: 6 },
  { prompt: 'What is 50 + 75?', answer: 125 },
  { prompt: 'In what year did World War II end?', answer: 1945 },
  { prompt: 'How many stripes are on the US flag?', answer: 13 },
  { prompt: 'How many states are in the United States?', answer: 50 },
  { prompt: 'In what year did the Titanic sink?', answer: 1912 },
  { prompt: 'How many players are on a basketball team on the court?', answer: 5 },
  { prompt: 'How many keys are on a standard piano?', answer: 88 },
  { prompt: 'How many bones are in the adult human body?', answer: 206 },
  { prompt: 'What is the boiling point of water in Fahrenheit?', answer: 212 },
  { prompt: 'How many continents are there?', answer: 7 },
  { prompt: 'How many degrees are in a right angle?', answer: 90 },
  { prompt: 'How many LOH wins is considered a record in one season?', answer: 13 },
  { prompt: 'What season introduced the Battle Back Shock?', answer: 18 },
  { prompt: 'How many days does a typical The Big Eye housemate stay before early elimination?', answer: 14 },
  { prompt: 'How many POS competitions have been won by nominees in The Big Eye history?', answer: 9 },
  { prompt: 'What season featured a twins-based Shock?', answer: 17 },
  { prompt: 'How many housemates competed in Season 21 of The Big Eye?', answer: 16 },
  { prompt: 'In what season did the LOH Blocker power first appear?', answer: 18 },
  { prompt: 'How many seasons has a solo winner competed in The Big Eye more than once?', answer: 2 },
  { prompt: 'What is the record for most LOH wins in one season?', answer: 5 },
  { prompt: 'How many Tribunal votes are needed for a tie in a 9-member Tribunal?', answer: 5 },
  { prompt: 'How many players start a game of chess?', answer: 2 },
  { prompt: 'How many cards are in a standard deck?', answer: 52 },
  { prompt: 'How many innings in a standard baseball game?', answer: 9 },
  { prompt: 'How many points is a touchdown worth in football?', answer: 6 },
  { prompt: 'How many strings does a standard guitar have?', answer: 6 },
  { prompt: 'How many squares are on a checkerboard?', answer: 64 },
  { prompt: 'How many planets are in our solar system?', answer: 8 },
  { prompt: 'How many Olympic rings are there?', answer: 5 },
  { prompt: 'How many seconds are in 5 minutes?', answer: 300 },
  { prompt: 'What is 25% of 80?', answer: 20 },
  { prompt: 'How many housemates entered Season 23 of The Big Eye?', answer: 16 },
  { prompt: 'What season introduced the Safety Trial competitions?', answer: 19 },
  { prompt: 'How many times can a housemate be nominated in one season?', answer: 5 },
  { prompt: 'How many POS competitions did a legendary player win in Season 15?', answer: 0 },
  { prompt: 'What season had the most Double Elimination Shocks?', answer: 23 },
  { prompt: 'How many days does a housemate typically survive without a LOH win?', answer: 39 },
  { prompt: 'In what season did the Mentors Shock occur?', answer: 14 },
  { prompt: 'How many LOH and POS competitions did a legendary Season 13 player win?', answer: 10 },
  { prompt: 'What is the record for longest LOH competition (in hours)?', answer: 14 },
  { prompt: 'How many housemates made it to the Tribunal in Season 24?', answer: 9 },
  { prompt: 'How many letters are in the English alphabet?', answer: 26 },
  { prompt: 'How many hours are in a week?', answer: 168 },
  { prompt: 'What is 10 squared?', answer: 100 },
  { prompt: 'How many cents are in a dollar?', answer: 100 },
  { prompt: 'How many yards are in a football field?', answer: 100 },
  { prompt: 'How many black keys are on a piano?', answer: 36 },
  { prompt: 'How many teeth does an adult human have?', answer: 32 },
  { prompt: 'How many ounces are in a pound?', answer: 16 },
  { prompt: 'How many millimeters are in a centimeter?', answer: 10 },
  { prompt: 'What is the freezing point of water in Celsius?', answer: 0 },
  { prompt: 'How many elimination votes did the Season 19 runner-up receive?', answer: 5 },
  { prompt: 'How many days was a Season 20 housemate in the house before early exit?', answer: 23 },
  { prompt: 'What season featured the first winner from a non-majority alliance?', answer: 10 },
  { prompt: 'How many housemates in Season 7 had previously played the game?', answer: 14 },
  { prompt: 'How many POS competitions did a Season 12 fan-favourite win?', answer: 4 },
  { prompt: 'What season introduced the Comfort/Scarcity Shock?', answer: 9 },
  { prompt: 'How many unanimous eliminations occurred in The Big Eye through Season 25?', answer: 38 },
  { prompt: 'How many former winners competed in Season 22?', answer: 5 },
  { prompt: 'How many seasons of The Big Eye aired in 2020?', answer: 1 },
  { prompt: 'What is the minimum age to apply for The Big Eye?', answer: 21 },
  { prompt: 'How many faces does a cube have?', answer: 6 },
  { prompt: 'How many months have 31 days?', answer: 7 },
  { prompt: 'How many zeros are in one million?', answer: 6 },
  { prompt: 'What is 3 cubed (3³)?', answer: 27 },
  { prompt: 'How many degrees are in a circle?', answer: 360 },
  { prompt: 'How many quarts are in a gallon?', answer: 4 },
  { prompt: 'How many hours ahead is GMT from EST?', answer: 5 },
  { prompt: 'How many innings are in a cricket test match (per team)?', answer: 2 },
  { prompt: 'How many permanent members are on the UN Security Council?', answer: 5 },
  { prompt: 'What is the atomic number of carbon?', answer: 6 },
];
