from __future__ import annotations

import json
from pathlib import Path

MESSAGES = Path('src/i18n/messages.ts')
COMPONENT = Path('src/components/TetrisComp/TetrisComp.tsx')

KEYS = {
    'fitMeIn.description': 'Survive an adaptive multi-round fitting tournament and reach the Houseguest Mosaic Final.',
    'fitMeIn.rules.freshBoard': 'Every round starts on a fresh board and has a fixed time limit.',
    'fitMeIn.rules.fivePlus': 'With 5 or more players, the last-ranked player leaves after rounds 1 and 2; round 3 keeps only the top 2.',
    'fitMeIn.rules.fourPlayers': 'With 4 players, last place leaves in round 1 and round 2 keeps the top 2.',
    'fitMeIn.rules.threePlayers': 'With 3 players, a 90-second semifinal keeps the top 2.',
    'fitMeIn.rules.mosaicFinal': 'The final is a fresh head-to-head board. Its locked squares become mini houseguest avatars.',
    'fitMeIn.rules.scoring': 'Score comes from line clears and controlled drops. The highest final-round score wins.',
    'fitMeIn.round.semifinal': 'Semifinal',
    'fitMeIn.round.topTwoAdvance': 'Top 2 advance',
    'fitMeIn.round.mosaicFinal': 'Houseguest Mosaic Final',
    'fitMeIn.round.highestScoreWins': 'Highest score wins',
    'fitMeIn.round.openingHeat': 'Opening Heat',
    'fitMeIn.round.lastPlaceEliminated': 'Last place is eliminated',
    'fitMeIn.round.pressureRound': 'Pressure Round',
    'fitMeIn.round.progress': 'Round {current} of {total}',
    'fitMeIn.round.complete': '{round} complete',
    'fitMeIn.round.qualified': 'You are through to the next round.',
    'fitMeIn.round.eliminatedMessage': 'You have been eliminated. The remaining houseguests will finish the tournament.',
    'fitMeIn.round.standings': 'Round standings',
    'fitMeIn.youTag': '(you)',
    'fitMeIn.finishingTournament': 'Finishing tournament…',
    'fitMeIn.enterFinal': 'Enter the Final',
    'fitMeIn.nextRound': 'Next Round',
    'fitMeIn.revealWinner': 'Reveal the Winner',
    'fitMeIn.youWin': 'You Win!',
    'fitMeIn.playerWins': '{name} Wins!',
    'fitMeIn.finalComplete': 'The Houseguest Mosaic Final is complete.',
    'fitMeIn.yourLastScore': 'Your last score:',
    'fitMeIn.levelUp': '⬆ LEVEL {level}!',
    'fitMeIn.timeUp': 'TIME!',
    'fitMeIn.toppedOut': 'TOPPED OUT',
    'fitMeIn.calculatingStandings': 'Calculating round standings…',
    'fitMeIn.control.hold': 'Hold',
    'fitMeIn.control.rotate': 'Rotate',
    'fitMeIn.control.hardDrop': 'Hard drop',
    'fitMeIn.control.moveLeft': 'Move left',
    'fitMeIn.control.softDrop': 'Soft drop',
    'fitMeIn.control.moveRight': 'Move right',
    'fitMeIn.status.safe': 'SAFE',
    'fitMeIn.status.eliminated': 'ELIMINATED',
}

TRANSLATIONS = {
    'FR_FR_MESSAGES': {
        'fitMeIn.description': 'Survivez à un tournoi adaptatif en plusieurs manches et atteignez la finale Mosaïque des candidats.',
        'fitMeIn.rules.freshBoard': 'Chaque manche commence sur une grille vide et possède une limite de temps fixe.',
        'fitMeIn.rules.fivePlus': 'Avec 5 joueurs ou plus, le dernier du classement quitte la partie après les manches 1 et 2 ; la manche 3 ne garde que les 2 meilleurs.',
        'fitMeIn.rules.fourPlayers': 'Avec 4 joueurs, le dernier quitte la partie à la manche 1 et la manche 2 ne garde que les 2 meilleurs.',
        'fitMeIn.rules.threePlayers': 'Avec 3 joueurs, une demi-finale de 90 secondes qualifie les 2 meilleurs.',
        'fitMeIn.rules.mosaicFinal': 'La finale se joue en duel sur une grille neuve. Les cases verrouillées deviennent de petits portraits des candidats.',
        'fitMeIn.rules.scoring': 'Vous marquez des points en supprimant des lignes et avec les chutes contrôlées. Le meilleur score de la finale gagne.',
        'fitMeIn.round.semifinal': 'Demi-finale',
        'fitMeIn.round.topTwoAdvance': 'Les 2 meilleurs se qualifient',
        'fitMeIn.round.mosaicFinal': 'Finale Mosaïque des candidats',
        'fitMeIn.round.highestScoreWins': 'Le meilleur score gagne',
        'fitMeIn.round.openingHeat': 'Manche d’ouverture',
        'fitMeIn.round.lastPlaceEliminated': 'Le dernier est éliminé',
        'fitMeIn.round.pressureRound': 'Manche sous pression',
        'fitMeIn.round.progress': 'Manche {current} sur {total}',
        'fitMeIn.round.complete': '{round} terminée',
        'fitMeIn.round.qualified': 'Vous passez à la manche suivante.',
        'fitMeIn.round.eliminatedMessage': 'Vous êtes éliminé. Les candidats restants termineront le tournoi.',
        'fitMeIn.round.standings': 'Classement de la manche',
        'fitMeIn.youTag': '(vous)',
        'fitMeIn.finishingTournament': 'Fin du tournoi en cours…',
        'fitMeIn.enterFinal': 'Accéder à la finale',
        'fitMeIn.nextRound': 'Manche suivante',
        'fitMeIn.revealWinner': 'Révéler le vainqueur',
        'fitMeIn.youWin': 'Vous gagnez !',
        'fitMeIn.playerWins': '{name} gagne !',
        'fitMeIn.finalComplete': 'La finale Mosaïque des candidats est terminée.',
        'fitMeIn.yourLastScore': 'Votre dernier score :',
        'fitMeIn.levelUp': '⬆ NIVEAU {level} !',
        'fitMeIn.timeUp': 'TEMPS ÉCOULÉ !',
        'fitMeIn.toppedOut': 'GRILLE BLOQUÉE',
        'fitMeIn.calculatingStandings': 'Calcul du classement de la manche…',
        'fitMeIn.control.hold': 'Réserver',
        'fitMeIn.control.rotate': 'Tourner',
        'fitMeIn.control.hardDrop': 'Chute rapide',
        'fitMeIn.control.moveLeft': 'Déplacer à gauche',
        'fitMeIn.control.softDrop': 'Descente douce',
        'fitMeIn.control.moveRight': 'Déplacer à droite',
        'fitMeIn.status.safe': 'QUALIFIÉ',
        'fitMeIn.status.eliminated': 'ÉLIMINÉ',
    },
    'IT_IT_MESSAGES': {
        'fitMeIn.description': 'Sopravvivi a un torneo adattivo a più round e raggiungi la finale Mosaico dei concorrenti.',
        'fitMeIn.rules.freshBoard': 'Ogni round inizia con una griglia vuota e ha un limite di tempo fisso.',
        'fitMeIn.rules.fivePlus': 'Con 5 o più giocatori, l’ultimo in classifica viene eliminato dopo i round 1 e 2; il round 3 mantiene solo i primi 2.',
        'fitMeIn.rules.fourPlayers': 'Con 4 giocatori, l’ultimo viene eliminato nel round 1 e il round 2 mantiene i primi 2.',
        'fitMeIn.rules.threePlayers': 'Con 3 giocatori, una semifinale di 90 secondi qualifica i primi 2.',
        'fitMeIn.rules.mosaicFinal': 'La finale è un duello su una griglia nuova. Le caselle bloccate diventano mini avatar dei concorrenti.',
        'fitMeIn.rules.scoring': 'Ottieni punti cancellando linee e con le cadute controllate. Vince il punteggio più alto nel round finale.',
        'fitMeIn.round.semifinal': 'Semifinale',
        'fitMeIn.round.topTwoAdvance': 'Passano i primi 2',
        'fitMeIn.round.mosaicFinal': 'Finale Mosaico dei concorrenti',
        'fitMeIn.round.highestScoreWins': 'Vince il punteggio più alto',
        'fitMeIn.round.openingHeat': 'Manche iniziale',
        'fitMeIn.round.lastPlaceEliminated': 'L’ultimo viene eliminato',
        'fitMeIn.round.pressureRound': 'Round di pressione',
        'fitMeIn.round.progress': 'Round {current} di {total}',
        'fitMeIn.round.complete': '{round} completato',
        'fitMeIn.round.qualified': 'Hai superato il round e vai avanti.',
        'fitMeIn.round.eliminatedMessage': 'Sei stato eliminato. Gli altri concorrenti completeranno il torneo.',
        'fitMeIn.round.standings': 'Classifica del round',
        'fitMeIn.youTag': '(tu)',
        'fitMeIn.finishingTournament': 'Completamento del torneo…',
        'fitMeIn.enterFinal': 'Entra nella finale',
        'fitMeIn.nextRound': 'Round successivo',
        'fitMeIn.revealWinner': 'Rivela il vincitore',
        'fitMeIn.youWin': 'Hai vinto!',
        'fitMeIn.playerWins': 'Vince {name}!',
        'fitMeIn.finalComplete': 'La finale Mosaico dei concorrenti è terminata.',
        'fitMeIn.yourLastScore': 'Il tuo ultimo punteggio:',
        'fitMeIn.levelUp': '⬆ LIVELLO {level}!',
        'fitMeIn.timeUp': 'TEMPO SCADUTO!',
        'fitMeIn.toppedOut': 'GRIGLIA PIENA',
        'fitMeIn.calculatingStandings': 'Calcolo della classifica del round…',
        'fitMeIn.control.hold': 'Conserva',
        'fitMeIn.control.rotate': 'Ruota',
        'fitMeIn.control.hardDrop': 'Caduta rapida',
        'fitMeIn.control.moveLeft': 'Sposta a sinistra',
        'fitMeIn.control.softDrop': 'Discesa lenta',
        'fitMeIn.control.moveRight': 'Sposta a destra',
        'fitMeIn.status.safe': 'SALVO',
        'fitMeIn.status.eliminated': 'ELIMINATO',
    },
    'ES_ES_MESSAGES': {
        'fitMeIn.description': 'Sobrevive a un torneo adaptativo de varias rondas y llega a la final Mosaico de concursantes.',
        'fitMeIn.rules.freshBoard': 'Cada ronda empieza con un tablero vacío y tiene un límite de tiempo fijo.',
        'fitMeIn.rules.fivePlus': 'Con 5 jugadores o más, el último clasificado sale tras las rondas 1 y 2; la ronda 3 conserva solo a los 2 mejores.',
        'fitMeIn.rules.fourPlayers': 'Con 4 jugadores, el último sale en la ronda 1 y la ronda 2 conserva a los 2 mejores.',
        'fitMeIn.rules.threePlayers': 'Con 3 jugadores, una semifinal de 90 segundos clasifica a los 2 mejores.',
        'fitMeIn.rules.mosaicFinal': 'La final es un duelo en un tablero nuevo. Las casillas fijadas se convierten en miniavatares de los concursantes.',
        'fitMeIn.rules.scoring': 'Suma puntos al completar líneas y con caídas controladas. Gana la puntuación más alta de la ronda final.',
        'fitMeIn.round.semifinal': 'Semifinal',
        'fitMeIn.round.topTwoAdvance': 'Avanzan los 2 mejores',
        'fitMeIn.round.mosaicFinal': 'Final Mosaico de concursantes',
        'fitMeIn.round.highestScoreWins': 'Gana la puntuación más alta',
        'fitMeIn.round.openingHeat': 'Ronda inicial',
        'fitMeIn.round.lastPlaceEliminated': 'El último queda eliminado',
        'fitMeIn.round.pressureRound': 'Ronda de presión',
        'fitMeIn.round.progress': 'Ronda {current} de {total}',
        'fitMeIn.round.complete': '{round} completada',
        'fitMeIn.round.qualified': 'Pasas a la siguiente ronda.',
        'fitMeIn.round.eliminatedMessage': 'Has sido eliminado. Los concursantes restantes terminarán el torneo.',
        'fitMeIn.round.standings': 'Clasificación de la ronda',
        'fitMeIn.youTag': '(tú)',
        'fitMeIn.finishingTournament': 'Finalizando el torneo…',
        'fitMeIn.enterFinal': 'Entrar en la final',
        'fitMeIn.nextRound': 'Siguiente ronda',
        'fitMeIn.revealWinner': 'Revelar al ganador',
        'fitMeIn.youWin': '¡Has ganado!',
        'fitMeIn.playerWins': '¡Gana {name}!',
        'fitMeIn.finalComplete': 'La final Mosaico de concursantes ha terminado.',
        'fitMeIn.yourLastScore': 'Tu última puntuación:',
        'fitMeIn.levelUp': '⬆ ¡NIVEL {level}!',
        'fitMeIn.timeUp': '¡TIEMPO!',
        'fitMeIn.toppedOut': 'TABLERO LLENO',
        'fitMeIn.calculatingStandings': 'Calculando la clasificación de la ronda…',
        'fitMeIn.control.hold': 'Guardar',
        'fitMeIn.control.rotate': 'Girar',
        'fitMeIn.control.hardDrop': 'Caída rápida',
        'fitMeIn.control.moveLeft': 'Mover a la izquierda',
        'fitMeIn.control.softDrop': 'Caída suave',
        'fitMeIn.control.moveRight': 'Mover a la derecha',
        'fitMeIn.status.safe': 'A SALVO',
        'fitMeIn.status.eliminated': 'ELIMINADO',
    },
    'PT_PT_MESSAGES': {
        'fitMeIn.description': 'Sobrevive a um torneio adaptativo de várias rondas e chega à final Mosaico dos concorrentes.',
        'fitMeIn.rules.freshBoard': 'Cada ronda começa com um tabuleiro vazio e tem um limite de tempo fixo.',
        'fitMeIn.rules.fivePlus': 'Com 5 ou mais jogadores, o último classificado sai após as rondas 1 e 2; a ronda 3 mantém apenas os 2 melhores.',
        'fitMeIn.rules.fourPlayers': 'Com 4 jogadores, o último sai na ronda 1 e a ronda 2 mantém os 2 melhores.',
        'fitMeIn.rules.threePlayers': 'Com 3 jogadores, uma semifinal de 90 segundos apura os 2 melhores.',
        'fitMeIn.rules.mosaicFinal': 'A final é um duelo num tabuleiro novo. As casas fixadas tornam-se miniavatares dos concorrentes.',
        'fitMeIn.rules.scoring': 'Ganha pontos ao completar linhas e com quedas controladas. A maior pontuação da ronda final vence.',
        'fitMeIn.round.semifinal': 'Semifinal',
        'fitMeIn.round.topTwoAdvance': 'Avançam os 2 melhores',
        'fitMeIn.round.mosaicFinal': 'Final Mosaico dos concorrentes',
        'fitMeIn.round.highestScoreWins': 'A maior pontuação vence',
        'fitMeIn.round.openingHeat': 'Ronda de abertura',
        'fitMeIn.round.lastPlaceEliminated': 'O último é eliminado',
        'fitMeIn.round.pressureRound': 'Ronda de pressão',
        'fitMeIn.round.progress': 'Ronda {current} de {total}',
        'fitMeIn.round.complete': '{round} concluída',
        'fitMeIn.round.qualified': 'Passaste à ronda seguinte.',
        'fitMeIn.round.eliminatedMessage': 'Foste eliminado. Os concorrentes restantes terminarão o torneio.',
        'fitMeIn.round.standings': 'Classificação da ronda',
        'fitMeIn.youTag': '(tu)',
        'fitMeIn.finishingTournament': 'A terminar o torneio…',
        'fitMeIn.enterFinal': 'Entrar na final',
        'fitMeIn.nextRound': 'Ronda seguinte',
        'fitMeIn.revealWinner': 'Revelar o vencedor',
        'fitMeIn.youWin': 'Venceste!',
        'fitMeIn.playerWins': '{name} vence!',
        'fitMeIn.finalComplete': 'A final Mosaico dos concorrentes terminou.',
        'fitMeIn.yourLastScore': 'A tua última pontuação:',
        'fitMeIn.levelUp': '⬆ NÍVEL {level}!',
        'fitMeIn.timeUp': 'TEMPO!',
        'fitMeIn.toppedOut': 'TABULEIRO CHEIO',
        'fitMeIn.calculatingStandings': 'A calcular a classificação da ronda…',
        'fitMeIn.control.hold': 'Guardar',
        'fitMeIn.control.rotate': 'Rodar',
        'fitMeIn.control.hardDrop': 'Queda rápida',
        'fitMeIn.control.moveLeft': 'Mover para a esquerda',
        'fitMeIn.control.softDrop': 'Queda suave',
        'fitMeIn.control.moveRight': 'Mover para a direita',
        'fitMeIn.status.safe': 'SEGURO',
        'fitMeIn.status.eliminated': 'ELIMINADO',
    },
    'DE_DE_MESSAGES': {
        'fitMeIn.description': 'Überstehe ein adaptives Turnier über mehrere Runden und erreiche das Hausgast-Mosaik-Finale.',
        'fitMeIn.rules.freshBoard': 'Jede Runde beginnt mit einem leeren Spielfeld und hat ein festes Zeitlimit.',
        'fitMeIn.rules.fivePlus': 'Bei 5 oder mehr Spielern scheidet nach Runde 1 und 2 jeweils der Letztplatzierte aus; in Runde 3 bleiben nur die besten 2.',
        'fitMeIn.rules.fourPlayers': 'Bei 4 Spielern scheidet in Runde 1 der Letztplatzierte aus, und Runde 2 lässt die besten 2 weiterkommen.',
        'fitMeIn.rules.threePlayers': 'Bei 3 Spielern erreichen die besten 2 nach einem 90-sekündigen Halbfinale das Finale.',
        'fitMeIn.rules.mosaicFinal': 'Das Finale ist ein direktes Duell auf einem neuen Feld. Festgesetzte Kästchen werden zu Mini-Avataren der Hausgäste.',
        'fitMeIn.rules.scoring': 'Punkte gibt es für vollständige Linien und kontrollierte Drops. Die höchste Punktzahl der Finalrunde gewinnt.',
        'fitMeIn.round.semifinal': 'Halbfinale',
        'fitMeIn.round.topTwoAdvance': 'Die besten 2 kommen weiter',
        'fitMeIn.round.mosaicFinal': 'Hausgast-Mosaik-Finale',
        'fitMeIn.round.highestScoreWins': 'Die höchste Punktzahl gewinnt',
        'fitMeIn.round.openingHeat': 'Auftaktrunde',
        'fitMeIn.round.lastPlaceEliminated': 'Der letzte Platz scheidet aus',
        'fitMeIn.round.pressureRound': 'Druckrunde',
        'fitMeIn.round.progress': 'Runde {current} von {total}',
        'fitMeIn.round.complete': '{round} beendet',
        'fitMeIn.round.qualified': 'Du bist für die nächste Runde qualifiziert.',
        'fitMeIn.round.eliminatedMessage': 'Du bist ausgeschieden. Die übrigen Hausgäste spielen das Turnier zu Ende.',
        'fitMeIn.round.standings': 'Rundenwertung',
        'fitMeIn.youTag': '(du)',
        'fitMeIn.finishingTournament': 'Turnier wird beendet…',
        'fitMeIn.enterFinal': 'Finale betreten',
        'fitMeIn.nextRound': 'Nächste Runde',
        'fitMeIn.revealWinner': 'Sieger anzeigen',
        'fitMeIn.youWin': 'Du gewinnst!',
        'fitMeIn.playerWins': '{name} gewinnt!',
        'fitMeIn.finalComplete': 'Das Hausgast-Mosaik-Finale ist beendet.',
        'fitMeIn.yourLastScore': 'Deine letzte Punktzahl:',
        'fitMeIn.levelUp': '⬆ LEVEL {level}!',
        'fitMeIn.timeUp': 'ZEIT ABGELAUFEN!',
        'fitMeIn.toppedOut': 'SPIELFELD VOLL',
        'fitMeIn.calculatingStandings': 'Rundenwertung wird berechnet…',
        'fitMeIn.control.hold': 'Halten',
        'fitMeIn.control.rotate': 'Drehen',
        'fitMeIn.control.hardDrop': 'Schnell fallen',
        'fitMeIn.control.moveLeft': 'Nach links bewegen',
        'fitMeIn.control.softDrop': 'Langsam fallen',
        'fitMeIn.control.moveRight': 'Nach rechts bewegen',
        'fitMeIn.status.safe': 'SICHER',
        'fitMeIn.status.eliminated': 'AUSGESCHIEDEN',
    },
    'ZH_CN_MESSAGES': {
        'fitMeIn.description': '在自适应多轮拼图淘汰赛中坚持到底，晋级“住客马赛克”决赛。',
        'fitMeIn.rules.freshBoard': '每轮都从空棋盘开始，并设有固定时间限制。',
        'fitMeIn.rules.fivePlus': '5名或更多玩家参赛时，第1轮和第2轮各淘汰排名最后者；第3轮只保留前2名。',
        'fitMeIn.rules.fourPlayers': '4名玩家参赛时，第1轮淘汰最后一名，第2轮保留前2名。',
        'fitMeIn.rules.threePlayers': '3名玩家参赛时，通过90秒半决赛决出前2名。',
        'fitMeIn.rules.mosaicFinal': '决赛在全新棋盘上进行一对一对决。锁定方块会变成随机住客的迷你头像。',
        'fitMeIn.rules.scoring': '消除整行和受控下落可获得分数。决赛轮得分最高者获胜。',
        'fitMeIn.round.semifinal': '半决赛',
        'fitMeIn.round.topTwoAdvance': '前2名晋级',
        'fitMeIn.round.mosaicFinal': '住客马赛克决赛',
        'fitMeIn.round.highestScoreWins': '最高分获胜',
        'fitMeIn.round.openingHeat': '首轮赛',
        'fitMeIn.round.lastPlaceEliminated': '最后一名淘汰',
        'fitMeIn.round.pressureRound': '压力轮',
        'fitMeIn.round.progress': '第 {current} 轮，共 {total} 轮',
        'fitMeIn.round.complete': '{round}结束',
        'fitMeIn.round.qualified': '你已晋级下一轮。',
        'fitMeIn.round.eliminatedMessage': '你已被淘汰。其余住客将完成比赛。',
        'fitMeIn.round.standings': '本轮排名',
        'fitMeIn.youTag': '（你）',
        'fitMeIn.finishingTournament': '正在完成比赛…',
        'fitMeIn.enterFinal': '进入决赛',
        'fitMeIn.nextRound': '下一轮',
        'fitMeIn.revealWinner': '揭晓获胜者',
        'fitMeIn.youWin': '你赢了！',
        'fitMeIn.playerWins': '{name}获胜！',
        'fitMeIn.finalComplete': '住客马赛克决赛已结束。',
        'fitMeIn.yourLastScore': '你的上一轮得分：',
        'fitMeIn.levelUp': '⬆ 等级 {level}！',
        'fitMeIn.timeUp': '时间到！',
        'fitMeIn.toppedOut': '棋盘已满',
        'fitMeIn.calculatingStandings': '正在计算本轮排名…',
        'fitMeIn.control.hold': '暂存',
        'fitMeIn.control.rotate': '旋转',
        'fitMeIn.control.hardDrop': '快速下落',
        'fitMeIn.control.moveLeft': '向左移动',
        'fitMeIn.control.softDrop': '缓慢下落',
        'fitMeIn.control.moveRight': '向右移动',
        'fitMeIn.status.safe': '晋级',
        'fitMeIn.status.eliminated': '淘汰',
    },
    'BG_BG_MESSAGES': {
        'fitMeIn.description': 'Оцелей в адаптивен турнир от няколко рунда и стигни до финала „Мозайка от съквартиранти“.',
        'fitMeIn.rules.freshBoard': 'Всеки рунд започва с празно поле и има фиксирано времетраене.',
        'fitMeIn.rules.fivePlus': 'При 5 или повече играчи последният в класирането отпада след рундове 1 и 2, а рунд 3 оставя само първите 2.',
        'fitMeIn.rules.fourPlayers': 'При 4 играчи последният отпада в рунд 1, а рунд 2 оставя първите 2.',
        'fitMeIn.rules.threePlayers': 'При 3 играчи 90-секунден полуфинал определя първите 2.',
        'fitMeIn.rules.mosaicFinal': 'Финалът е директен двубой на чисто поле. Заключените квадратчета се превръщат в миниаватари на съквартиранти.',
        'fitMeIn.rules.scoring': 'Печелиш точки с изчистени линии и контролирани спускания. Най-високият резултат във финалния рунд печели.',
        'fitMeIn.round.semifinal': 'Полуфинал',
        'fitMeIn.round.topTwoAdvance': 'Първите 2 продължават',
        'fitMeIn.round.mosaicFinal': 'Финал „Мозайка от съквартиранти“',
        'fitMeIn.round.highestScoreWins': 'Най-високият резултат печели',
        'fitMeIn.round.openingHeat': 'Откриващ рунд',
        'fitMeIn.round.lastPlaceEliminated': 'Последният отпада',
        'fitMeIn.round.pressureRound': 'Рунд под напрежение',
        'fitMeIn.round.progress': 'Рунд {current} от {total}',
        'fitMeIn.round.complete': '{round} приключи',
        'fitMeIn.round.qualified': 'Продължаваш към следващия рунд.',
        'fitMeIn.round.eliminatedMessage': 'Ти отпадна. Останалите съквартиранти ще довършат турнира.',
        'fitMeIn.round.standings': 'Класиране за рунда',
        'fitMeIn.youTag': '(ти)',
        'fitMeIn.finishingTournament': 'Турнирът приключва…',
        'fitMeIn.enterFinal': 'Към финала',
        'fitMeIn.nextRound': 'Следващ рунд',
        'fitMeIn.revealWinner': 'Покажи победителя',
        'fitMeIn.youWin': 'Ти печелиш!',
        'fitMeIn.playerWins': '{name} печели!',
        'fitMeIn.finalComplete': 'Финалът „Мозайка от съквартиранти“ приключи.',
        'fitMeIn.yourLastScore': 'Последният ти резултат:',
        'fitMeIn.levelUp': '⬆ НИВО {level}!',
        'fitMeIn.timeUp': 'ВРЕМЕТО ИЗТЕЧЕ!',
        'fitMeIn.toppedOut': 'ПОЛЕТО Е ПЪЛНО',
        'fitMeIn.calculatingStandings': 'Изчисляване на класирането…',
        'fitMeIn.control.hold': 'Задръж',
        'fitMeIn.control.rotate': 'Завърти',
        'fitMeIn.control.hardDrop': 'Пусни бързо',
        'fitMeIn.control.moveLeft': 'Премести наляво',
        'fitMeIn.control.softDrop': 'Спусни бавно',
        'fitMeIn.control.moveRight': 'Премести надясно',
        'fitMeIn.status.safe': 'ПРОДЪЛЖАВА',
        'fitMeIn.status.eliminated': 'ОТПАДА',
    },
    'RU_RU_MESSAGES': {
        'fitMeIn.description': 'Пройдите адаптивный турнир из нескольких раундов и доберитесь до финала «Мозаика участников».',
        'fitMeIn.rules.freshBoard': 'Каждый раунд начинается с пустого поля и имеет фиксированное ограничение времени.',
        'fitMeIn.rules.fivePlus': 'При 5 и более игроках после 1-го и 2-го раундов выбывает последний в рейтинге; в 3-м раунде остаются только двое лучших.',
        'fitMeIn.rules.fourPlayers': 'При 4 игроках последний выбывает в 1-м раунде, а 2-й раунд оставляет двоих лучших.',
        'fitMeIn.rules.threePlayers': 'При 3 игроках 90-секундный полуфинал определяет двоих лучших.',
        'fitMeIn.rules.mosaicFinal': 'Финал — очная дуэль на новом поле. Закреплённые клетки превращаются в мини-аватары участников.',
        'fitMeIn.rules.scoring': 'Очки начисляются за очищенные линии и контролируемое падение. Побеждает лучший результат финального раунда.',
        'fitMeIn.round.semifinal': 'Полуфинал',
        'fitMeIn.round.topTwoAdvance': 'Двое лучших проходят дальше',
        'fitMeIn.round.mosaicFinal': 'Финал «Мозаика участников»',
        'fitMeIn.round.highestScoreWins': 'Побеждает лучший результат',
        'fitMeIn.round.openingHeat': 'Стартовый раунд',
        'fitMeIn.round.lastPlaceEliminated': 'Последнее место выбывает',
        'fitMeIn.round.pressureRound': 'Раунд давления',
        'fitMeIn.round.progress': 'Раунд {current} из {total}',
        'fitMeIn.round.complete': '{round} завершён',
        'fitMeIn.round.qualified': 'Вы проходите в следующий раунд.',
        'fitMeIn.round.eliminatedMessage': 'Вы выбыли. Оставшиеся участники завершат турнир.',
        'fitMeIn.round.standings': 'Результаты раунда',
        'fitMeIn.youTag': '(вы)',
        'fitMeIn.finishingTournament': 'Завершение турнира…',
        'fitMeIn.enterFinal': 'Перейти в финал',
        'fitMeIn.nextRound': 'Следующий раунд',
        'fitMeIn.revealWinner': 'Показать победителя',
        'fitMeIn.youWin': 'Вы победили!',
        'fitMeIn.playerWins': 'Побеждает {name}!',
        'fitMeIn.finalComplete': 'Финал «Мозаика участников» завершён.',
        'fitMeIn.yourLastScore': 'Ваш последний результат:',
        'fitMeIn.levelUp': '⬆ УРОВЕНЬ {level}!',
        'fitMeIn.timeUp': 'ВРЕМЯ ВЫШЛО!',
        'fitMeIn.toppedOut': 'ПОЛЕ ЗАПОЛНЕНО',
        'fitMeIn.calculatingStandings': 'Подсчёт результатов раунда…',
        'fitMeIn.control.hold': 'Сохранить',
        'fitMeIn.control.rotate': 'Повернуть',
        'fitMeIn.control.hardDrop': 'Быстро сбросить',
        'fitMeIn.control.moveLeft': 'Сдвинуть влево',
        'fitMeIn.control.softDrop': 'Медленно опустить',
        'fitMeIn.control.moveRight': 'Сдвинуть вправо',
        'fitMeIn.status.safe': 'ПРОШЁЛ',
        'fitMeIn.status.eliminated': 'ВЫБЫЛ',
    },
    'UK_UA_MESSAGES': {
        'fitMeIn.description': 'Пройдіть адаптивний турнір із кількох раундів і дістаньтеся фіналу «Мозаїка учасників».',
        'fitMeIn.rules.freshBoard': 'Кожен раунд починається з порожнього поля та має фіксоване обмеження часу.',
        'fitMeIn.rules.fivePlus': 'За участі 5 або більше гравців після 1-го й 2-го раундів вибуває останній у рейтингу; у 3-му раунді залишаються лише двоє найкращих.',
        'fitMeIn.rules.fourPlayers': 'За участі 4 гравців останній вибуває в 1-му раунді, а 2-й раунд залишає двох найкращих.',
        'fitMeIn.rules.threePlayers': 'За участі 3 гравців 90-секундний півфінал визначає двох найкращих.',
        'fitMeIn.rules.mosaicFinal': 'Фінал — очна дуель на новому полі. Зафіксовані клітинки перетворюються на мініаватари учасників.',
        'fitMeIn.rules.scoring': 'Очки нараховуються за очищені лінії та контрольовані падіння. Перемагає найвищий результат фінального раунду.',
        'fitMeIn.round.semifinal': 'Півфінал',
        'fitMeIn.round.topTwoAdvance': 'Двоє найкращих проходять далі',
        'fitMeIn.round.mosaicFinal': 'Фінал «Мозаїка учасників»',
        'fitMeIn.round.highestScoreWins': 'Перемагає найвищий результат',
        'fitMeIn.round.openingHeat': 'Стартовий раунд',
        'fitMeIn.round.lastPlaceEliminated': 'Останнє місце вибуває',
        'fitMeIn.round.pressureRound': 'Раунд тиску',
        'fitMeIn.round.progress': 'Раунд {current} із {total}',
        'fitMeIn.round.complete': '{round} завершено',
        'fitMeIn.round.qualified': 'Ви проходите до наступного раунду.',
        'fitMeIn.round.eliminatedMessage': 'Ви вибули. Решта учасників завершать турнір.',
        'fitMeIn.round.standings': 'Результати раунду',
        'fitMeIn.youTag': '(ви)',
        'fitMeIn.finishingTournament': 'Завершення турніру…',
        'fitMeIn.enterFinal': 'Перейти до фіналу',
        'fitMeIn.nextRound': 'Наступний раунд',
        'fitMeIn.revealWinner': 'Показати переможця',
        'fitMeIn.youWin': 'Ви перемогли!',
        'fitMeIn.playerWins': 'Перемагає {name}!',
        'fitMeIn.finalComplete': 'Фінал «Мозаїка учасників» завершено.',
        'fitMeIn.yourLastScore': 'Ваш останній результат:',
        'fitMeIn.levelUp': '⬆ РІВЕНЬ {level}!',
        'fitMeIn.timeUp': 'ЧАС ВИЙШОВ!',
        'fitMeIn.toppedOut': 'ПОЛЕ ЗАПОВНЕНО',
        'fitMeIn.calculatingStandings': 'Підрахунок результатів раунду…',
        'fitMeIn.control.hold': 'Зберегти',
        'fitMeIn.control.rotate': 'Повернути',
        'fitMeIn.control.hardDrop': 'Швидко скинути',
        'fitMeIn.control.moveLeft': 'Посунути ліворуч',
        'fitMeIn.control.softDrop': 'Повільно опустити',
        'fitMeIn.control.moveRight': 'Посунути праворуч',
        'fitMeIn.status.safe': 'ПРОЙШОВ',
        'fitMeIn.status.eliminated': 'ВИБУВ',
    },
    'TR_TR_MESSAGES': {
        'fitMeIn.description': 'Uyarlanan çok turlu yerleştirme turnuvasında hayatta kal ve Ev Sakini Mozaik Finali’ne ulaş.',
        'fitMeIn.rules.freshBoard': 'Her tur boş bir tahtayla başlar ve sabit bir süre sınırı vardır.',
        'fitMeIn.rules.fivePlus': '5 veya daha fazla oyuncuda 1. ve 2. turlardan sonra sıralamanın sonundaki oyuncu elenir; 3. turda yalnızca ilk 2 kalır.',
        'fitMeIn.rules.fourPlayers': '4 oyuncuda 1. turda son sıradaki elenir, 2. turda ilk 2 kalır.',
        'fitMeIn.rules.threePlayers': '3 oyuncuda 90 saniyelik yarı final ilk 2’yi belirler.',
        'fitMeIn.rules.mosaicFinal': 'Final, yeni bir tahtada bire bir oynanır. Kilitlenen kareler rastgele ev sakinlerinin mini avatarlarına dönüşür.',
        'fitMeIn.rules.scoring': 'Tamamlanan satırlar ve kontrollü düşüşler puan kazandırır. Final turundaki en yüksek puan kazanır.',
        'fitMeIn.round.semifinal': 'Yarı final',
        'fitMeIn.round.topTwoAdvance': 'İlk 2 ilerler',
        'fitMeIn.round.mosaicFinal': 'Ev Sakini Mozaik Finali',
        'fitMeIn.round.highestScoreWins': 'En yüksek puan kazanır',
        'fitMeIn.round.openingHeat': 'Açılış turu',
        'fitMeIn.round.lastPlaceEliminated': 'Son sıradaki elenir',
        'fitMeIn.round.pressureRound': 'Baskı turu',
        'fitMeIn.round.progress': 'Tur {current}/{total}',
        'fitMeIn.round.complete': '{round} tamamlandı',
        'fitMeIn.round.qualified': 'Sonraki tura geçtin.',
        'fitMeIn.round.eliminatedMessage': 'Elendin. Kalan ev sakinleri turnuvayı tamamlayacak.',
        'fitMeIn.round.standings': 'Tur sıralaması',
        'fitMeIn.youTag': '(sen)',
        'fitMeIn.finishingTournament': 'Turnuva tamamlanıyor…',
        'fitMeIn.enterFinal': 'Finale gir',
        'fitMeIn.nextRound': 'Sonraki tur',
        'fitMeIn.revealWinner': 'Kazananı göster',
        'fitMeIn.youWin': 'Kazandın!',
        'fitMeIn.playerWins': '{name} kazandı!',
        'fitMeIn.finalComplete': 'Ev Sakini Mozaik Finali tamamlandı.',
        'fitMeIn.yourLastScore': 'Son puanın:',
        'fitMeIn.levelUp': '⬆ SEVİYE {level}!',
        'fitMeIn.timeUp': 'SÜRE DOLDU!',
        'fitMeIn.toppedOut': 'TAHTA DOLDU',
        'fitMeIn.calculatingStandings': 'Tur sıralaması hesaplanıyor…',
        'fitMeIn.control.hold': 'Sakla',
        'fitMeIn.control.rotate': 'Döndür',
        'fitMeIn.control.hardDrop': 'Hızlı bırak',
        'fitMeIn.control.moveLeft': 'Sola taşı',
        'fitMeIn.control.softDrop': 'Yavaş indir',
        'fitMeIn.control.moveRight': 'Sağa taşı',
        'fitMeIn.status.safe': 'GÜVENDE',
        'fitMeIn.status.eliminated': 'ELENDİ',
    },
}


def insert_catalog_entries(text: str, catalog_name: str, values: dict[str, str]) -> str:
    marker = 'export const EN_US_MESSAGES = {' if catalog_name == 'EN_US_MESSAGES' else f'const {catalog_name} = {{'
    if marker not in text:
        raise RuntimeError(f'Missing catalog marker: {catalog_name}')
    if "'fitMeIn.description'" in text[text.index(marker):text.index(marker) + 5000]:
        return text
    lines = [f"  {json.dumps(key, ensure_ascii=False)}: {json.dumps(value, ensure_ascii=False)}," for key, value in values.items()]
    return text.replace(marker, marker + '\n' + '\n'.join(lines), 1)


def replace_once(text: str, old: str, new: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f'Expected one occurrence, found {count}: {old[:120]!r}')
    return text.replace(old, new, 1)


messages = MESSAGES.read_text(encoding='utf-8')
messages = insert_catalog_entries(messages, 'EN_US_MESSAGES', KEYS)
for catalog, values in TRANSLATIONS.items():
    missing = set(KEYS) - set(values)
    extra = set(values) - set(KEYS)
    if missing or extra:
        raise RuntimeError(f'{catalog} key mismatch: missing={sorted(missing)}, extra={sorted(extra)}')
    messages = insert_catalog_entries(messages, catalog, values)
MESSAGES.write_text(messages, encoding='utf-8')

component = COMPONENT.read_text(encoding='utf-8')
component = replace_once(
    component,
    "import { useAppDispatch } from '../../store/hooks'",
    "import { useI18n } from '../../i18n/I18nContext'\nimport { useAppDispatch } from '../../store/hooks'",
)
component = replace_once(
    component,
    "  const dispatch = useAppDispatch()\n",
    "  const dispatch = useAppDispatch()\n  const { t } = useI18n()\n",
)
component = replace_once(
    component,
    "function formatTimer(milliseconds: number): string {\n",
    "function placementLabel(index: number): string {\n  return String(index + 1).concat('.')\n}\n\nfunction formatTimer(milliseconds: number): string {\n",
)
component = replace_once(
    component,
    """          <p className=\"tetris-round-results-kicker\">\n            Round {roundResult.plan.roundNumber} of {roundResult.plan.totalRounds}\n          </p>\n          <h2>{roundResult.plan.label} complete</h2>\n          <p className=\"tetris-round-results-summary\">\n            {humanStillActive\n              ? 'You are through to the next round.'\n              : 'You have been eliminated. The remaining houseguests will finish the tournament.'}\n          </p>\n          <ol className=\"tetris-round-standings\" aria-label=\"Round standings\">""",
    """          <p className=\"tetris-round-results-kicker\">\n            {t('fitMeIn.round.progress', {\n              current: roundResult.plan.roundNumber,\n              total: roundResult.plan.totalRounds,\n            })}\n          </p>\n          <h2>\n            {t('fitMeIn.round.complete', { round: t(roundResult.plan.labelKey) })}\n          </h2>\n          <p className=\"tetris-round-results-summary\">\n            {humanStillActive\n              ? t('fitMeIn.round.qualified')\n              : t('fitMeIn.round.eliminatedMessage')}\n          </p>\n          <ol\n            className=\"tetris-round-standings\"\n            aria-label={t('fitMeIn.round.standings')}\n          >""",
)
component = component.replace("MEDALS[index] ?? `${index + 1}.`", "MEDALS[index] ?? placementLabel(index)")
component = component.replace("participant?.isHuman ? ' (you)' : ''", "participant?.isHuman ? ` ${t('fitMeIn.youTag')}` : ''")
component = component.replace("<span className=\"tetris-results-you-tag\"> (you)</span>", "<span className=\"tetris-results-you-tag\"> {t('fitMeIn.youTag')}</span>")
component = replace_once(
    component,
    """            {simulatingRemainder\n              ? 'Finishing tournament…'\n              : humanStillActive\n                ? currentRoundIndex + 1 === tournamentPlan.length - 1\n                  ? 'Enter the Final'\n                  : 'Next Round'\n                : 'Reveal the Winner'}""",
    """            {simulatingRemainder\n              ? t('fitMeIn.finishingTournament')\n              : humanStillActive\n                ? currentRoundIndex + 1 === tournamentPlan.length - 1\n                  ? t('fitMeIn.enterFinal')\n                  : t('fitMeIn.nextRound')\n                : t('fitMeIn.revealWinner')}""",
)
component = replace_once(
    component,
    """            {winner?.isHuman ? 'You Win!' : `${winner?.name ?? finalResult.winnerId} Wins!`}\n          </h2>\n          <p className=\"tetris-results-subtitle\">The Houseguest Mosaic Final is complete.</p>\n          <div className=\"tetris-results-your-score\">\n            Your last score: <strong>{finalResult.humanScore.toLocaleString()}</strong>""",
    """            {winner?.isHuman\n              ? t('fitMeIn.youWin')\n              : t('fitMeIn.playerWins', { name: winner?.name ?? finalResult.winnerId })}\n          </h2>\n          <p className=\"tetris-results-subtitle\">{t('fitMeIn.finalComplete')}</p>\n          <div className=\"tetris-results-your-score\">\n            {t('fitMeIn.yourLastScore')} <strong>{finalResult.humanScore.toLocaleString()}</strong>""",
)
component = component.replace("<strong>{currentRound.label}</strong>", "<strong>{t(currentRound.labelKey)}</strong>")
component = component.replace("<small>{currentRound.subtitle}</small>", "<small>{t(currentRound.subtitleKey)}</small>")
component = replace_once(
    component,
    """        <div key={effect.id} className=\"tetris-levelup-overlay\" aria-live=\"polite\">\n          ⬆ LEVEL {effect.level}!\n        </div>""",
    """        <div key={effect.id} className=\"tetris-levelup-overlay\" aria-live=\"polite\">\n          {t('fitMeIn.levelUp', { level: effect.level })}\n        </div>""",
)
component = component.replace("{roundEndReason === 'time' ? 'TIME!' : 'TOPPED OUT'}", "{roundEndReason === 'time' ? t('fitMeIn.timeUp') : t('fitMeIn.toppedOut')}")
component = component.replace("<div className=\"tetris-gameover-sub\">Calculating round standings…</div>", "<div className=\"tetris-gameover-sub\">{t('fitMeIn.calculatingStandings')}</div>")
component = component.replace("{eliminated ? 'ELIMINATED' : 'SAFE'}", "{eliminated ? t('fitMeIn.status.eliminated') : t('fitMeIn.status.safe')}")
for old, key in [
    ('label=\"Hold\"', "label={t('fitMeIn.control.hold')}"),
    ('label=\"Rotate\"', "label={t('fitMeIn.control.rotate')}"),
    ('label=\"Hard drop\"', "label={t('fitMeIn.control.hardDrop')}"),
    ('label=\"Move left\"', "label={t('fitMeIn.control.moveLeft')}"),
    ('label=\"Soft drop\"', "label={t('fitMeIn.control.softDrop')}"),
    ('label=\"Move right\"', "label={t('fitMeIn.control.moveRight')}"),
]:
    component = component.replace(old, key)
COMPONENT.write_text(component, encoding='utf-8')
